package processor

type DataBasic struct {
	OutFlightDate          string
	OutFlightNo            string
	OutFlightDirection     string
	OutStatusName          string
	OutOperationStatusCode string
	OutCountryCode         string
	OutFlightTypeCode      string
	PortNoDp               string
	OutVipInd              string
	OutRunwayTypeCode      string
	OutEstripStatus        string
	OutRtPoint             string
	OutAirportRegion       string
	OutAirportRegionCn     string
	OutRouteFst            string
	OutToPath              string
	OutGateNo              string
	OutShareFlightNo       string
	OutRoute               string
	OutRoute_              string
	OutRouteCn             string
	OutTmi                 string
	Sobt                   string
	Stot                   string
	Cobt                   string
	FrontCobt              string
	Tobt                   string
	OutCtot                string
	OutLastTot             string
	OutAtot                string
	OutAsbt                string
	OutAebt                string
	OutAcct                string
	Aobt                   string
	OutPushTime            string
	OutArriveAirport       string
	ActBeginTime           string
	OutDeicingType         string
	EnterWaitingAreaTime   string
	RightIntoTime          string
	Aczt                   string
	Aezt                   string
	AwayApronTime_         string
	OutPlanNextArrival     string
	OutActualNextArrival   string
	BuyTicket              string
	AddDelayReason         string
	InnerDelayReason       string
	InnerDelayDesc         string
	AircraftTypeCode       string
	AircraftSizeCategory   string
	PlaneNo                string
	AirlineIata            string
	AirlineIcao            string
	InFlightDate           string
	InFlightNo             string
	InFlightDirection      string
	InStatusName           string
	InOperationStatusCode  string
	InCountryCode          string
	InFlightTypeCode       string
	PortNoLd               string
	InVipInd               string
	InRunwayTypeCode       string
	InEstripStatus         string
	InRtPoint              string
	InAirportRegion        string
	InAirportRegionCn      string
	InRtPoint_             string
	InToPath               string
	InShareFlightNo        string
	InRoute                string
	InRoute_               string
	InRouteCn              string
	InStot                 string
	InAtot                 string
	Sldt                   string
	Sibt                   string
	Eldt                   string
	Aldt                   string
	Aibt                   string
	OnBridgeTm             string
	Asot                   string
	InAeot                 string
	BaggageFirstTm         string
	BaggageLastTm          string
	FlightId               string
}
